NUMPY ARRAYS

In [2]:
print("Hello world")

Hello world


Numpy arrays

In [3]:
lst = [1,2,3,6]

In [4]:
import numpy as np


In [5]:
arr1 = np.array(lst)

In [6]:
print(arr1) 

[1 2 3 6]


In [7]:
arr1.shape

(4,)

2-D array

In [8]:
a = ([[1,2,6,0,3],
      [3,4,5,6,2],
      [9,7,0,1,8]])

In [9]:
arr = np.array(a)

In [10]:
arr[:,3:]

array([[0, 3],
       [6, 2],
       [1, 8]])

In [11]:
 arr[:, [0,-1]]


array([[1, 3],
       [3, 2],
       [9, 8]])

In [12]:
#EDA

In [13]:
a = ([[1,2,6,0,3],
      [3,4,5,6,2],
      [9,7,0,1,8]])

In [14]:
arr.shape

(3, 5)

In [15]:
arr.reshape(5,3,1)

array([[[1],
        [2],
        [6]],

       [[0],
        [3],
        [3]],

       [[4],
        [5],
        [6]],

       [[2],
        [9],
        [7]],

       [[0],
        [1],
        [8]]])

In [16]:
#mechanism to create array
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(1,20,2).reshape(2,5,1) #total 10 elements so reshape as 2*5*1

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]]])

In [19]:
arr * arr

array([[ 1,  4, 36,  0,  9],
       [ 9, 16, 25, 36,  4],
       [81, 49,  0,  1, 64]])

In [20]:
arr1* arr1

array([ 1,  4,  9, 36])

In [ ]:
#operations to perform 

In [21]:
np.ones((4,5))  #returns (4,5) shape ones array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.zeros((2,1))  #returns (2,1) shape 0 array

array([[0.],
       [0.]])

In [ ]:
np.random.randint(10,50,5)  # return 5 random int bw 1-50 

array([11, 17, 33, 32, 23], dtype=int32)

In [ ]:
np.random.randint(11,39,4).reshape(2,2)

array([[24, 21],
       [27, 16]], dtype=int32)

In [ ]:
np.random.randn(3,4)  #sample from standard normal distribution

array([[ 0.21795974,  1.13611953, -1.08858947,  0.9843382 ],
       [ 0.95735954,  0.72940261, -1.69908996, -0.59818958],
       [-1.00376573,  1.49212857, -0.76569344, -0.23171087]])

In [ ]:
np.random.random_sample((4,7))

array([[0.79116396, 0.7169395 , 0.71092002, 0.0905574 , 0.64391264,
        0.22696241, 0.52404179],
       [0.19934679, 0.09333684, 0.49159088, 0.43733504, 0.62007666,
        0.55332807, 0.69921277],
       [0.68400027, 0.61998776, 0.57791472, 0.20065384, 0.91691851,
        0.16084655, 0.87016134],
       [0.66771803, 0.80174604, 0.91560586, 0.740763  , 0.2024149 ,
        0.37268924, 0.59894014]])