NUMPY ARRAYS

In [2]:
print("Hello world")

Hello world


Numpy arrays

In [3]:
lst = [1,2,3,6]

In [4]:
import numpy as np


In [5]:
arr1 = np.array(lst)

In [6]:
print(arr1) 

[1 2 3 6]


In [7]:
arr1.shape

(4,)

2-D array

In [8]:
a = ([[1,2,6,0,3],
      [3,4,5,6,2],
      [9,7,0,1,8]])

In [9]:
arr = np.array(a)

In [10]:
arr[:,3:]

array([[0, 3],
       [6, 2],
       [1, 8]])

In [11]:
 arr[:, [0,-1]]


array([[1, 3],
       [3, 2],
       [9, 8]])

In [12]:
#EDA

In [13]:
a = ([[1,2,6,0,3],
      [3,4,5,6,2],
      [9,7,0,1,8]])

In [14]:
arr.shape

(3, 5)

In [15]:
arr.reshape(5,3,1)

array([[[1],
        [2],
        [6]],

       [[0],
        [3],
        [3]],

       [[4],
        [5],
        [6]],

       [[2],
        [9],
        [7]],

       [[0],
        [1],
        [8]]])

In [16]:
#mechanism to create array
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(1,20,2).reshape(2,5,1) #total 10 elements so reshape as 2*5*1

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]]])

In [18]:
arr * arr

array([[ 1,  4, 36,  0,  9],
       [ 9, 16, 25, 36,  4],
       [81, 49,  0,  1, 64]])

In [19]:
arr1* arr1

array([ 1,  4,  9, 36])

Initializing different arrays

In [21]:
np.ones((4,5))  #returns (4,5) shape ones array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.zeros((2,1))  #returns (2,1) shape 0 array

array([[0.],
       [0.]])

In [55]:
np.full((3,2),43)

array([[43, 43],
       [43, 43],
       [43, 43]])

In [ ]:
np.full_like(arr,21)   #shape like arr

array([[21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21]])

In [23]:
np.random.randint(10,50,5)  # return 5 random int bw 1-50 

array([46, 19, 29, 47, 41], dtype=int32)

In [24]:
np.random.randint(11,39,4).reshape(2,2)

array([[30, 30],
       [32, 37]], dtype=int32)

In [25]:
np.random.randn(3,4)  #sample from standard normal distribution

array([[-0.34142951, -0.17792941,  0.71065459,  1.20614328],
       [-0.61922969, -0.09276363, -1.42829644, -0.05434264],
       [ 1.07554434, -0.49703145,  0.4612533 ,  0.377259  ]])

In [26]:
np.random.random_sample((4,7))

array([[0.84439176, 0.23394733, 0.46157609, 0.01455321, 0.31978699,
        0.69473729, 0.00088458],
       [0.7874833 , 0.59743779, 0.1062003 , 0.61637806, 0.37785613,
        0.07491103, 0.27951448],
       [0.820719  , 0.11147646, 0.45221256, 0.53141946, 0.7473769 ,
        0.53755683, 0.78633784],
       [0.86382528, 0.61221652, 0.56713973, 0.72098485, 0.01164261,
        0.48487976, 0.17933995]])

In [65]:
#repeact an array
arr2 = np.array([[1,2,3],[4,5,6]])
arr3= np.repeat(arr2,3,axis=0)
print(arr3)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]]


In [58]:
#Identity matrix 
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [37]:
m = np.array([[1.1,3,5],[4,5,6]])
print(m)

[[1.1 3.  5. ]
 [4.  5.  6. ]]


In [38]:
#Get dimension
m.ndim

2

In [39]:
#Get shape
m.shape

(2, 3)

In [40]:
#get datatype
m.dtype

dtype('float64')

In [42]:
#get size
m.itemsize

8

In [43]:
#get total size
m.nbytes

48

3-D Array

In [49]:
n = np.array([[[1,2,3], [12,56,34]], [[67,90,38],[22,32,11]]])
print(n)
n.shape

[[[ 1  2  3]
  [12 56 34]]

 [[67 90 38]
  [22 32 11]]]


(2, 2, 3)

In [51]:
#get specific element 
n[0,1,1]

np.int64(56)

In [ ]:
#replace 
n[1,0:,1] =[5,10]
print(n)

[[[ 1  2  3]
  [12 56 34]]

 [[67  5 38]
  [22 10 11]]]
