NUMPY ARRAYS

In [2]:
print("Hello world")

Hello world


Numpy arrays

In [3]:
lst = [1,2,3,6]

In [4]:
import numpy as np


In [5]:
arr1 = np.array(lst)

In [6]:
print(arr1) 

[1 2 3 6]


In [7]:
arr1.shape

(4,)

2-D array

In [8]:
a = ([[1,2,6,0,3],
      [3,4,5,6,2],
      [9,7,0,1,8]])

In [9]:
arr = np.array(a)

In [10]:
arr[:,3:]

array([[0, 3],
       [6, 2],
       [1, 8]])

In [11]:
 arr[:, [0,-1]]


array([[1, 3],
       [3, 2],
       [9, 8]])

EDA

In [13]:
a = ([[1,2,6,0,3],
      [3,4,5,6,2],
      [9,7,0,1,8]])

In [14]:
arr.shape

(3, 5)

In [ ]:
#reshape array
arr.reshape(5,3,1)

array([[[1],
        [2],
        [6]],

       [[0],
        [3],
        [3]],

       [[4],
        [5],
        [6]],

       [[2],
        [9],
        [7]],

       [[0],
        [1],
        [8]]])

In [88]:
#flatten array
arr.flatten()

array([1, 2, 6, 0, 3, 3, 4, 5, 6, 2, 9, 7, 0, 1, 8])

In [16]:
#mechanism to create array
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(1,20,2).reshape(2,5,1) #total 10 elements so reshape as 2*5*1

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]]])

In [ ]:
#specific number of equally (spaced) values between a range
np.linspace(2,20,4)

array([ 2.,  8., 14., 20.])

In [18]:
arr * arr

array([[ 1,  4, 36,  0,  9],
       [ 9, 16, 25, 36,  4],
       [81, 49,  0,  1, 64]])

In [19]:
arr1* arr1

array([ 1,  4,  9, 36])

Initializing different arrays

In [20]:
np.ones((4,5))  #returns (4,5) shape ones array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.zeros((2,1))  #returns (2,1) shape 0 array

array([[0.],
       [0.]])

In [22]:
np.full((3,2),43)

array([[43, 43],
       [43, 43],
       [43, 43]])

In [23]:
np.full_like(arr,21)   #shape like arr

array([[21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21]])

In [24]:
np.random.randint(10,50,5)  # return 5 random int bw 1-50 

array([34, 41, 18, 29, 31], dtype=int32)

In [25]:
np.random.randint(11,39,4).reshape(2,2)

array([[22, 13],
       [31, 23]], dtype=int32)

In [26]:
np.random.randn(3,4)  #sample from standard normal distribution

array([[-5.55401923e-01, -7.65254656e-01,  1.98576746e-03,
         8.41019118e-01],
       [ 6.29851494e-02, -1.62655231e+00,  2.44786783e-01,
        -1.82175108e+00],
       [ 1.07394959e-02, -2.90288666e+00, -9.59657433e-01,
         1.28129928e+00]])

In [27]:
np.random.random_sample((4,7))

array([[0.12578036, 0.99660264, 0.43431673, 0.59128735, 0.08827322,
        0.46323143, 0.88422868],
       [0.56275143, 0.50700482, 0.64085187, 0.25930615, 0.79789121,
        0.21603175, 0.99759585],
       [0.57745351, 0.37674496, 0.95197853, 0.44777871, 0.64351687,
        0.31418485, 0.14564493],
       [0.11363328, 0.32493446, 0.13646059, 0.79021585, 0.36830425,
        0.17392014, 0.44327074]])

In [28]:
#repeact an array
arr2 = np.array([[1,2,3],[4,5,6]])
arr3= np.repeat(arr2,3,axis=0)
print(arr3)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]]


In [29]:
#Identity matrix 
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [30]:
m = np.array([[1.1,3,5],[4,5,6]])
print(m)

[[1.1 3.  5. ]
 [4.  5.  6. ]]


In [31]:
#Get dimension
m.ndim

2

In [32]:
#Get shape
m.shape

(2, 3)

In [33]:
#get datatype
m.dtype

dtype('float64')

In [34]:
#get size
m.itemsize

8

In [35]:
#get total size
m.nbytes

48

3-D Array

In [36]:
n = np.array([[[1,2,3], [12,56,34]], [[67,90,38],[22,32,11]]])
print(n)
n.shape

[[[ 1  2  3]
  [12 56 34]]

 [[67 90 38]
  [22 32 11]]]


(2, 2, 3)

In [37]:
#get specific element 
n[0,1,1]

np.int64(56)

In [38]:
#replace 
n[1,0:,1] =[5,10]
print(n)

[[[ 1  2  3]
  [12 56 34]]

 [[67  5 38]
  [22 10 11]]]


In [46]:
#Problem
a1 = np.ones((5,5))
a2 = np.zeros((3,3))
a1[ 1:4, 1:4] = a2

a1[2,2] = 9
print(a1)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Mathematics calculation

In [49]:
x = np.array([1,2,3])
print(x)
x + 2
x-2
x * x
x/2
print(x)

[1 2 3]
[1 2 3]


In [ ]:
#take sin and all trignometric functions
np.sin(x)

array([0.84147098, 0.90929743, 0.14112001])

LINEAR ALGEBRA

In [52]:
#matrix multipilcation
m1 = np.ones((2,3))
m2 = np.full((3,2),4)
np.matmul(m1,m2)

array([[12., 12.],
       [12., 12.]])

In [53]:
#find determinant
m3 = np.identity(3)
np.linalg.det(m3)

np.float64(1.0)

STATISTICS

In [56]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)


[[1 2 3]
 [4 5 6]]


In [59]:
np.min(stats)
np.max(stats,axis = 1)

array([3, 6])

In [60]:
np.mean(stats, axis = 0)

array([2.5, 3.5, 4.5])

In [62]:
stats = np.array([[1,2,3],[4,5,6]])
np.median(stats)

np.float64(3.5)

Rearranging arrays

In [ ]:
#horizontally stack arrays
v1 = np.ones((2,3))
v2 = np.full((2,3),5)
np.hstack([v1,v2])

array([[1., 1., 1., 5., 5., 5.],
       [1., 1., 1., 5., 5., 5.]])

In [93]:
#vertically stack arrays
k =np.vstack([v2,v1])
print(k)

[[5. 5. 5.]
 [5. 5. 5.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#horizontal spliting   - column wise
np.hsplit(k,3)

[array([[5.],
        [5.],
        [1.],
        [1.]]),
 array([[5.],
        [5.],
        [1.],
        [1.]]),
 array([[5.],
        [5.],
        [1.],
        [1.]])]

In [ ]:
#vertical splitting - row wise
np.vsplit(k,4)

[array([[5., 5., 5.]]),
 array([[5., 5., 5.]]),
 array([[1., 1., 1.]]),
 array([[1., 1., 1.]])]

Load data from file

In [79]:
filedate = np.genfromtxt(r"a.txt")
print(filedate)

[[ 1.  2.  3.  4.  5.  5.  6.  7.  8.]
 [ 2.  4.  5.  6.  7.  8. 90.  8.  0.]]


Boolean masking

In [80]:
filedate > 20

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False,  True, False, False]])

In [82]:
filedate[filedate > 20]

array([90.])

In [83]:
((filedate > 10) & (filedate< 100))

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False,  True, False, False]])

Comparing elements

In [97]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [ ]:
print(a == b)  #compare each element

[False False False]


In [ ]:
print(np.array_equal(a,b))  # compare complete array

False


Broadcasting

In [ ]:
a = np.array([[11,2,3], [5,6,7]])
b = np.array([43,11,12])     #conevrt lower dimension array in higher dimension array and perform operation without throwing error
print(a + b)

[[54 13 15]
 [48 17 19]]


Handling null and infinite values

In [102]:
a = np.array([1,2,3,np.nan, 56, np.inf])
print(a)

[ 1.  2.  3. nan 56. inf]


In [104]:
print(np.isnan(a))

[False False False  True False False]


In [105]:
#change null values to numbers
print(np.nan_to_num(a))

[1.00000000e+000 2.00000000e+000 3.00000000e+000 0.00000000e+000
 5.60000000e+001 1.79769313e+308]


Save and load array

In [106]:
n1 = np.array([[1,2,3],[2,3,4]])
print(n1)

[[1 2 3]
 [2 3 4]]


In [ ]:
np.save('saved_array.npy',n1)  #save array

In [108]:
#load array
np.load('saved_array.npy')

array([[1, 2, 3],
       [2, 3, 4]])

In [112]:
np.arange((1,25),(5,5))

TypeError: arange: scalar arguments expected instead of a tuple.